file:
  directory: D:\Students\jang jin seong\download\tdd

spring:
  datasource:
    username: root
    password: green502
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3_test
  sql:
    init:
      mode: never
  # resources 아래의 schema.sql(테이블 생성 DDL) data.sql(데이터 insert DML)파일을
  # 프로젝트(테스트) 시작시 실행
  # sql init mode 는 상황에 따라 상태를 바꿈
  # never always 어떤 방식으로 사용?